#!/bin/bash

if [ "$1" = "--make" ]; then
        echo "wanda:f@rlY0ddp@r3nt5" | chpasswd
        echo "cosmo:1234" | chpasswd

        # total points you can earn
        echo "10"
fi

if [ "$1" = "--score" ]; then
        score=10

        export SALT=$(grep cosmo /etc/shadow | awk -F'$' '{print $4}')
        if [[ $(perl -e 'print crypt "1234", "\$y\$j9T\$$ENV{'SALT'}\$"') = $(grep cosmo /etc/shadow | awk -F':' '{print $2}') ]]; then
                score=$(($score - 10))
        fi

        echo $score 
fi

